# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(341, 326)
        self.gridLayoutWidget = QtWidgets.QWidget(widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 20, 271, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_4.setObjectName("lbl_4")
        self.gridLayout.addWidget(self.lbl_4, 3, 0, 1, 1)
        self.lbl_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_3.setObjectName("lbl_3")
        self.gridLayout.addWidget(self.lbl_3, 2, 0, 1, 1)
        self.lbl_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_2.setObjectName("lbl_2")
        self.gridLayout.addWidget(self.lbl_2, 1, 0, 1, 1)
        self.lbl_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_1.setObjectName("lbl_1")
        self.gridLayout.addWidget(self.lbl_1, 0, 0, 1, 1)
        self.lbl_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_6.setObjectName("lbl_6")
        self.gridLayout.addWidget(self.lbl_6, 5, 0, 1, 1)
        self.lbl_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_5.setObjectName("lbl_5")
        self.gridLayout.addWidget(self.lbl_5, 4, 0, 1, 1)
        self.le_sort = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.le_sort.setObjectName("le_sort")
        self.gridLayout.addWidget(self.le_sort, 0, 1, 1, 1)
        self.le_degree = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.le_degree.setObjectName("le_degree")
        self.gridLayout.addWidget(self.le_degree, 1, 1, 1, 1)
        self.le_ground = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.le_ground.setObjectName("le_ground")
        self.gridLayout.addWidget(self.le_ground, 2, 1, 1, 1)
        self.le_taste = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.le_taste.setObjectName("le_taste")
        self.gridLayout.addWidget(self.le_taste, 3, 1, 1, 1)
        self.le_cost = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.le_cost.setObjectName("le_cost")
        self.gridLayout.addWidget(self.le_cost, 4, 1, 1, 1)
        self.le_volume = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.le_volume.setObjectName("le_volume")
        self.gridLayout.addWidget(self.le_volume, 5, 1, 1, 1)
        self.btn_save = QtWidgets.QPushButton(widget)
        self.btn_save.setGeometry(QtCore.QRect(190, 270, 111, 31))
        self.btn_save.setObjectName("btn_save")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Добавление"))
        self.lbl_4.setText(_translate("widget", "Описание вкуса"))
        self.lbl_3.setText(_translate("widget", "Молотый/в зернах"))
        self.lbl_2.setText(_translate("widget", "Степень обжарки"))
        self.lbl_1.setText(_translate("widget", "Название сорта"))
        self.lbl_6.setText(_translate("widget", "Объем упаковки"))
        self.lbl_5.setText(_translate("widget", "Цена"))
        self.btn_save.setText(_translate("widget", "Сохранить"))
